/**
 * MEERAV VISUAL DESIGN EDITOR
 * Click-select any static element on the live storefront (rendered inside an
 * iframe), drag to move / resize, tweak colors, typography, media and links,
 * with full local undo/redo. Everything persists to localStorage only —
 * nothing touches Supabase yet. A tiny companion script
 * (js/apply-editor-patches.js) re-applies the same saved edits on the real
 * storefront pages so a reload shows the change "for real", browser-local.
 *
 * Elements that are generated by store.js/category-page.js/product-detail.js
 * from live DB data (product cards, cart, reviews, FAQs…) are intentionally
 * locked — editing their *content* belongs to the existing Admin CRM pages,
 * which already write straight to Supabase.
 */
const MiraEditor = (function () {
  const STORAGE_KEY = 'mira_editor_patches_v1';
  const UNDO_LIMIT = 100;

  const PAGES = {
    home: { file: 'index.html', label: 'Home' },
    category: { file: 'category.html', label: 'Category Explorer' },
    product: { file: 'product.html?id=p1', label: 'Product Detail' }
  };

  const LOCKED_SELECTORS = [
    '#products-grid', '#categories-container', '#dietary-container',
    '#home-category-showcase', '#reels-scroll-track', '#cart-items-container',
    '#cart-summary-container', '#home-testimonials-container', '#home-faqs-container',
    '#home-trust-badges-grid', '#home-stats-grid', '#home-story-paragraphs',
    '#toast-container', '#product-detail-modal', '#checkout-modal',
    '#payment-gateway-modal', '#wa-preview-body', '#email-preview-modal',
    '#category-picker-cards-grid', '#category-dietary-container', '#category-products-grid',
    '#category-empty-state', '#pdp-variants-container', '#pdp-slides-wrapper',
    '#pdp-thumbnails-row', '#pdp-related-grid', '#pdp-fullscreen-modal',
    '#live-tracking-view', '#order-tracking-map', '#checkout-map', '#address-map'
  ];

  const state = {
    pageKey: 'home',
    iframe: null,
    doc: null,
    win: null,
    selectedEl: null,
    selectedPath: null,
    hoveredEl: null,
    patches: loadPatches(),
    undoStack: [],
    redoStack: [],
    gridSnap: 8,
    snapEnabled: true,
    previewMode: false,
    currentAdmin: null,
    adminUserId: null
  };

  // ---------------------------------------------------------------- storage
  function loadPatches() {
    try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || {}; } catch (e) { return {}; }
  }
  function savePatches() {
    try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state.patches)); } catch (e) {
      flashToast('Local storage is full — a media file may be too large.');
    }
    flashStatus('All changes saved locally · ' + new Date().toLocaleTimeString('en-IN'));
  }
  function pagePatches() {
    if (!state.patches[state.pageKey]) state.patches[state.pageKey] = {};
    return state.patches[state.pageKey];
  }

  // ------------------------------------------------------------ element path
  function getPath(el) {
    if (!el || el.nodeType !== 1) return '';
    if (el.tagName === 'BODY') return 'body';
    const parent = el.parentElement;
    if (!parent) return el.tagName.toLowerCase();
    const idx = Array.prototype.indexOf.call(parent.children, el) + 1;
    return getPath(parent) + ' > ' + el.tagName.toLowerCase() + ':nth-child(' + idx + ')';
  }

  function isLocked(el) {
    if (!el || !state.doc) return true;
    if (el === state.doc.body || el.tagName === 'HTML') return true;
    if (['SCRIPT', 'STYLE', 'LINK', 'META', 'HEAD', 'TITLE'].includes(el.tagName)) return true;
    for (const sel of LOCKED_SELECTORS) {
      const container = state.doc.querySelector(sel);
      if (container && (container === el || container.contains(el))) return true;
    }
    return false;
  }

  // ------------------------------------------------------------- undo/redo
  function pushUndo() {
    state.undoStack.push(JSON.stringify(pagePatches()));
    if (state.undoStack.length > UNDO_LIMIT) state.undoStack.shift();
    state.redoStack = [];
    updateUndoRedoButtons();
  }

  function undo() {
    if (!state.undoStack.length) return;
    const current = JSON.stringify(pagePatches());
    const prev = state.undoStack.pop();
    state.redoStack.push(current);
    state.patches[state.pageKey] = JSON.parse(prev);
    savePatches();
    reloadAndApply(reselectByPath);
    updateUndoRedoButtons();
  }

  function redo() {
    if (!state.redoStack.length) return;
    const current = JSON.stringify(pagePatches());
    const next = state.redoStack.pop();
    state.undoStack.push(current);
    state.patches[state.pageKey] = JSON.parse(next);
    savePatches();
    reloadAndApply(reselectByPath);
    updateUndoRedoButtons();
  }

  function updateUndoRedoButtons() {
    const u = document.getElementById('ed-undo-btn');
    const r = document.getElementById('ed-redo-btn');
    if (u) u.disabled = state.undoStack.length === 0;
    if (r) r.disabled = state.redoStack.length === 0;
  }

  // ------------------------------------------------------------ page loading
  function loadPage(pageKey) {
    state.pageKey = pageKey;
    const info = PAGES[pageKey];
    const select = document.getElementById('ed-page-select');
    if (select) select.value = pageKey;

    state.selectedEl = null;
    state.selectedPath = null;
    state.undoStack = [];
    state.redoStack = [];
    updateUndoRedoButtons();
    renderPropertiesPanel();

    const iframe = document.getElementById('ed-iframe');
    state.iframe = iframe;
    const sep = info.file.includes('?') ? '&' : '?';
    iframe.onload = bootstrapIframe;
    iframe.src = info.file + sep + 'edmode=1&t=' + Date.now();
  }

  function reloadAndApply(cb) {
    if (!state.iframe) return;
    state.iframe.onload = () => { bootstrapIframe(); if (cb) cb(); };
    try { state.iframe.contentWindow.location.reload(); } catch (e) { loadPage(state.pageKey); }
  }

  function bootstrapIframe() {
    const iframe = state.iframe;
    if (!iframe || !iframe.contentDocument) return;
    state.doc = iframe.contentDocument;
    state.win = iframe.contentWindow;
    // The page itself already ran js/apply-editor-patches.js on load (it's
    // the real index.html/category.html/product.html, script tags and all)
    // — only fall back to applying patches here if that didn't happen for
    // some reason, otherwise every "Add Element"/Block would get inserted
    // twice.
    if (!state.win.__miraPatchesApplied) applyAllPatches();
    attachSelectionListeners();
    populateSwatches();
    renderLayers();
    flashStatus('Page loaded · edits from this browser applied');
  }

  function applyAllPatches() {
    const patches = pagePatches();
    // pass 1: mutations on elements that already exist in the page HTML
    Object.keys(patches).forEach((key) => {
      if (key.indexOf('__insert_') === 0) return;
      const p = patches[key];
      const el = state.doc.querySelector(key);
      if (!el) return;
      if (p.deleted) { el.remove(); return; }
      if (p.style) Object.assign(el.style, p.style);
      if (p.attrs) Object.entries(p.attrs).forEach(([k, v]) => el.setAttribute(k, v));
      if (p.text != null && el.children.length === 0) el.textContent = p.text;
    });
    // pass 2: elements added via the "Add Element" palette — recreated from
    // their saved markup and appended to their parent, in save order.
    Object.keys(patches).forEach((key) => {
      if (key.indexOf('__insert_') !== 0) return;
      if (state.doc.querySelector('[data-ed-id="' + key + '"]')) return;
      const p = patches[key];
      const parent = state.doc.querySelector(p.parentPath);
      if (!parent) return;
      const wrap = state.doc.createElement('div');
      wrap.innerHTML = p.html;
      const node = wrap.firstElementChild;
      if (node) parent.appendChild(node);
    });
  }

  function reselectByPath() {
    if (!state.selectedPath || !state.doc) { renderPropertiesPanel(); renderOverlay(); return; }
    const el = state.doc.querySelector(state.selectedPath);
    if (el) selectElement(el);
    else { state.selectedEl = null; renderPropertiesPanel(); renderOverlay(); }
  }

  // ------------------------------------------------------------- selection
  function attachSelectionListeners() {
    const body = state.doc.body;
    body.addEventListener('mouseover', onMouseOver);
    body.addEventListener('mouseout', onMouseOut);
    body.addEventListener('click', onClick, true);
    body.addEventListener('dblclick', onDblClick, true);
    body.addEventListener('submit', (e) => e.preventDefault(), true);
    state.win.addEventListener('scroll', renderOverlay);
    state.win.addEventListener('resize', renderOverlay);
    bindKeyboardShortcuts(state.doc);
  }

  function onMouseOver(e) {
    if (state.previewMode) return;
    state.hoveredEl = e.target;
    renderOverlay();
  }
  function onMouseOut() {
    state.hoveredEl = null;
    renderOverlay();
  }
  function onClick(e) {
    if (state.previewMode) return;
    e.preventDefault();
    e.stopPropagation();
    const el = e.target;
    if (isLocked(el)) {
      flashToast('This section is generated from live data — edit it from the matching Admin CRM page instead.');
      return;
    }
    selectElement(el);
  }
  function onDblClick(e) {
    if (state.previewMode) return;
    const el = e.target;
    if (isLocked(el) || el.children.length > 0) return;
    e.preventDefault();
    e.stopPropagation();
    pushUndo();
    el.contentEditable = 'true';
    el.focus();
    document.execCommand && document.execCommand('selectAll', false, null);
    const onBlur = () => {
      el.contentEditable = 'false';
      const insertedRoot = findInsertedRoot(el);
      if (insertedRoot) {
        syncInsertedNode(insertedRoot);
      } else {
        const path = getPath(el);
        const patches = pagePatches();
        if (!patches[path]) patches[path] = {};
        patches[path].text = el.textContent;
        savePatches();
      }
      el.removeEventListener('blur', onBlur);
    };
    el.addEventListener('blur', onBlur);
  }

  function selectElement(el) {
    state.selectedEl = el;
    state.selectedPath = getPath(el);
    renderOverlay();
    renderPropertiesPanel();
    highlightActiveLayer();
  }

  function highlightActiveLayer() {
    const container = document.getElementById('ed-layers-tree');
    if (!container) return;
    container.querySelectorAll('.ed-layer-item.active').forEach((n) => n.classList.remove('active'));
    if (!state.selectedPath) return;
    const row = container.querySelector(`.ed-layer-item[data-path="${escapeAttr(state.selectedPath).replace(/"/g, '\\"')}"]`);
    if (row) row.classList.add('active');
  }

  function describeEl(el) {
    let d = el.tagName.toLowerCase();
    if (el.id) d += '#' + el.id;
    else if (el.className && typeof el.className === 'string' && el.className.trim()) {
      d += '.' + el.className.trim().split(/\s+/)[0];
    }
    return d;
  }

  // ---------------------------------------------------------------- overlay
  function elRectToViewport(el) {
    const r = el.getBoundingClientRect();
    const ir = state.iframe.getBoundingClientRect();
    return { left: ir.left + r.left, top: ir.top + r.top, width: r.width, height: r.height };
  }

  function renderOverlay() {
    const hoverBox = document.getElementById('ed-hover-box');
    const selectBox = document.getElementById('ed-select-box');
    const selectLabel = document.getElementById('ed-select-label');
    const dragHandle = document.getElementById('ed-drag-handle');
    const resizeHandle = document.getElementById('ed-resize-handle');
    if (!hoverBox) return;

    if (!state.previewMode && state.hoveredEl && state.hoveredEl !== state.selectedEl && state.hoveredEl.isConnected && !isLocked(state.hoveredEl)) {
      const r = elRectToViewport(state.hoveredEl);
      Object.assign(hoverBox.style, { display: 'block', left: r.left + 'px', top: r.top + 'px', width: r.width + 'px', height: r.height + 'px' });
    } else {
      hoverBox.style.display = 'none';
    }

    if (!state.previewMode && state.selectedEl && state.selectedEl.isConnected) {
      const r = elRectToViewport(state.selectedEl);
      Object.assign(selectBox.style, { display: 'block', left: r.left + 'px', top: r.top + 'px', width: r.width + 'px', height: r.height + 'px' });
      selectLabel.style.display = 'block';
      selectLabel.style.left = r.left + 'px';
      selectLabel.style.top = (r.top - 20) + 'px';
      selectLabel.textContent = describeEl(state.selectedEl);
      dragHandle.style.display = 'flex';
      dragHandle.style.left = (r.left - 22) + 'px';
      dragHandle.style.top = r.top + 'px';
      resizeHandle.style.display = 'block';
      resizeHandle.style.left = (r.left + r.width - 6) + 'px';
      resizeHandle.style.top = (r.top + r.height - 6) + 'px';
    } else {
      selectBox.style.display = 'none';
      selectLabel.style.display = 'none';
      dragHandle.style.display = 'none';
      resizeHandle.style.display = 'none';
    }
  }

  // ---------------------------------------------------------------- commit
  // Elements inserted by the "Add Element"/"Blocks" palette don't exist in
  // the original page HTML, so they can't be found again via a CSS path —
  // the block's OUTERMOST node carries a permanent data-ed-id and the whole
  // subtree is persisted as one self-contained "recreate this markup"
  // record (see insertElement / applyAllPatches pass 2). Editing something
  // *inside* a block (a card's photo, its button text…) still needs to
  // persist, so any commit walks up to that root and re-serializes the
  // whole block rather than trying to path-address the nested node.
  function findInsertedRoot(el) {
    let node = el;
    while (node && node.nodeType === 1) {
      const id = node.getAttribute && node.getAttribute('data-ed-id');
      if (id && id.indexOf('__insert_') === 0) return node;
      node = node.parentElement;
    }
    return null;
  }
  function syncInsertedNode(root) {
    const id = root.getAttribute('data-ed-id');
    const patches = pagePatches();
    if (patches[id]) { patches[id].html = root.outerHTML; savePatches(); }
  }

  function commitStyle(el, props) {
    const root = findInsertedRoot(el);
    if (root) { syncInsertedNode(root); return; }
    const path = getPath(el);
    const patches = pagePatches();
    if (!patches[path]) patches[path] = {};
    if (!patches[path].style) patches[path].style = {};
    props.forEach((p) => {
      const val = el.style[p];
      if (val) patches[path].style[p] = val; else delete patches[path].style[p];
    });
    savePatches();
  }
  function commitAttr(el, attr, val) {
    const root = findInsertedRoot(el);
    if (root) { syncInsertedNode(root); return; }
    const path = getPath(el);
    const patches = pagePatches();
    if (!patches[path]) patches[path] = {};
    if (!patches[path].attrs) patches[path].attrs = {};
    patches[path].attrs[attr] = val;
    savePatches();
  }
  function migratePatchKey(oldPath, newPath) {
    if (oldPath === newPath) return;
    const patches = pagePatches();
    if (patches[oldPath]) { patches[newPath] = patches[oldPath]; delete patches[oldPath]; }
  }

  // ------------------------------------------------------------- drag / resize
  function initDragHandle() {
    const handle = document.getElementById('ed-drag-handle');
    handle.addEventListener('mousedown', (e) => {
      e.preventDefault();
      if (!state.selectedEl) return;
      pushUndo();
      const el = state.selectedEl;
      const startMouseX = e.clientX, startMouseY = e.clientY;
      const cs = state.win.getComputedStyle(el);
      const startLeft = parseFloat(cs.left) || 0;
      const startTop = parseFloat(cs.top) || 0;
      if (!['relative', 'absolute', 'fixed'].includes(cs.position)) el.style.position = 'relative';

      function onMove(ev) {
        let dx = ev.clientX - startMouseX;
        let dy = ev.clientY - startMouseY;
        if (state.snapEnabled) {
          dx = Math.round(dx / state.gridSnap) * state.gridSnap;
          dy = Math.round(dy / state.gridSnap) * state.gridSnap;
        }
        el.style.left = (startLeft + dx) + 'px';
        el.style.top = (startTop + dy) + 'px';
        renderOverlay();
      }
      function onUp() {
        document.removeEventListener('mousemove', onMove);
        document.removeEventListener('mouseup', onUp);
        commitStyle(el, ['position', 'left', 'top']);
      }
      document.addEventListener('mousemove', onMove);
      document.addEventListener('mouseup', onUp);
    });
  }

  function initResizeHandle() {
    const handle = document.getElementById('ed-resize-handle');
    handle.addEventListener('mousedown', (e) => {
      e.preventDefault(); e.stopPropagation();
      if (!state.selectedEl) return;
      pushUndo();
      const el = state.selectedEl;
      const startMouseX = e.clientX, startMouseY = e.clientY;
      const rect = el.getBoundingClientRect();
      const startW = rect.width, startH = rect.height;
      el.style.boxSizing = 'border-box';

      function onMove(ev) {
        let dw = ev.clientX - startMouseX;
        let dh = ev.clientY - startMouseY;
        let newW = Math.max(20, startW + dw);
        let newH = Math.max(20, startH + dh);
        if (state.snapEnabled) {
          newW = Math.round(newW / state.gridSnap) * state.gridSnap;
          newH = Math.round(newH / state.gridSnap) * state.gridSnap;
        }
        el.style.width = newW + 'px';
        el.style.height = newH + 'px';
        renderOverlay();
        const w = document.getElementById('ed-width-input');
        const h = document.getElementById('ed-height-input');
        if (w) w.value = Math.round(newW);
        if (h) h.value = Math.round(newH);
      }
      function onUp() {
        document.removeEventListener('mousemove', onMove);
        document.removeEventListener('mouseup', onUp);
        commitStyle(el, ['boxSizing', 'width', 'height']);
      }
      document.addEventListener('mousemove', onMove);
      document.addEventListener('mouseup', onUp);
    });
  }

  function moveSibling(direction) {
    const el = state.selectedEl;
    if (!el) return;
    const parent = el.parentElement;
    const sib = direction === 'up' ? el.previousElementSibling : el.nextElementSibling;
    if (!sib || isLocked(sib)) { flashToast('No movable sibling in that direction.'); return; }
    pushUndo();
    const oldPathEl = getPath(el), oldPathSib = getPath(sib);
    if (direction === 'up') parent.insertBefore(el, sib); else parent.insertBefore(sib, el);
    migratePatchKey(oldPathEl, getPath(el));
    migratePatchKey(oldPathSib, getPath(sib));
    savePatches();
    state.selectedPath = getPath(el);
    renderOverlay();
    renderLayers();
    flashToast('Reordered');
  }

  function resetPosition() {
    if (!state.selectedEl) return;
    pushUndo();
    const el = state.selectedEl;
    ['position', 'left', 'top'].forEach((p) => { el.style[p] = ''; });
    commitStyle(el, ['position', 'left', 'top']);
    renderOverlay();
  }

  function bringToFront() {
    if (!state.selectedEl) return;
    pushUndo();
    const el = state.selectedEl;
    const cs = state.win.getComputedStyle(el);
    if (!['relative', 'absolute', 'fixed', 'sticky'].includes(cs.position)) el.style.position = 'relative';
    el.style.zIndex = '999';
    commitStyle(el, ['position', 'zIndex']);
    flashToast('Brought to front');
  }
  function sendToBack() {
    if (!state.selectedEl) return;
    pushUndo();
    const el = state.selectedEl;
    const cs = state.win.getComputedStyle(el);
    if (!['relative', 'absolute', 'fixed', 'sticky'].includes(cs.position)) el.style.position = 'relative';
    el.style.zIndex = '-1';
    commitStyle(el, ['position', 'zIndex']);
    flashToast('Sent to back');
  }

  // ------------------------------------------------------------ add element
  let insertCounter = 0;
  function ELEMENT_TEMPLATES(win) {
    const doc = win.document;
    return {
      heading: () => { const el = doc.createElement('h2'); el.textContent = 'New Heading'; el.style.cssText = 'font-weight:900;font-size:28px;color:#4A0713;margin:12px 0;'; return el; },
      text: () => { const el = doc.createElement('p'); el.textContent = 'Edit this text…'; el.style.cssText = 'font-size:14px;color:#374151;margin:8px 0;line-height:1.6;'; return el; },
      button: () => { const el = doc.createElement('a'); el.textContent = 'Click Me'; el.setAttribute('href', 'index.html'); el.style.cssText = 'display:inline-block;padding:10px 20px;background:#4A0713;color:#FBBF24;border-radius:12px;font-weight:800;text-decoration:none;margin:8px 0;'; return el; },
      image: () => { const el = doc.createElement('img'); el.setAttribute('src', 'assets/images/cinematic_bhujia.jpg'); el.setAttribute('alt', 'New image'); el.style.cssText = 'width:220px;height:160px;object-fit:cover;border-radius:14px;margin:8px 0;display:block;'; return el; },
      container: () => { const el = doc.createElement('div'); el.style.cssText = 'padding:24px;border:2px dashed #E59819;border-radius:16px;min-height:70px;margin:12px 0;'; return el; },
      spacer: () => { const el = doc.createElement('div'); el.style.cssText = 'height:40px;'; return el; },
      divider: () => { const el = doc.createElement('hr'); el.style.cssText = 'border:none;border-top:3px solid #E59819;margin:16px 0;width:100%;'; return el; },
      rectangle: () => { const el = doc.createElement('div'); el.style.cssText = 'width:200px;height:100px;background:#4A0713;border-radius:8px;margin:8px 0;'; return el; },
      circle: () => { const el = doc.createElement('div'); el.style.cssText = 'width:100px;height:100px;background:#E59819;border-radius:50%;margin:8px 0;'; return el; },
      icon: () => { const el = doc.createElement('span'); el.style.cssText = 'display:inline-flex;align-items:center;justify-content:center;width:56px;height:56px;background:#4A0713;color:#FBBF24;border-radius:50%;font-size:22px;margin:8px 0;'; el.innerHTML = '<i class="fas fa-star"></i>'; return el; }
    };
  }

  // Ready-made multi-element blocks (Blocks tab). Each factory builds a full
  // subtree — once inserted, every photo/heading/button inside it is still
  // individually clickable and editable (see findInsertedRoot above), it's
  // only the *insertion* that happens as one unit.
  function BLOCK_TEMPLATES(win) {
    const doc = win.document;
    return {
      imageCard: () => {
        const card = doc.createElement('div');
        card.style.cssText = 'max-width:280px;background:#fff;border:2px solid #fed7aa;border-radius:16px;overflow:hidden;margin:12px 0;box-shadow:0 4px 14px rgba(0,0,0,.08);';
        const img = doc.createElement('img');
        img.setAttribute('src', 'assets/images/cinematic_bhujia.jpg');
        img.setAttribute('alt', 'Card photo');
        img.style.cssText = 'width:100%;height:160px;object-fit:cover;display:block;';
        const body = doc.createElement('div');
        body.style.cssText = 'padding:16px;';
        const h = doc.createElement('h3'); h.textContent = 'Card Title'; h.style.cssText = 'font-weight:900;font-size:16px;color:#4A0713;margin:0 0 6px;';
        const p = doc.createElement('p'); p.textContent = 'Short description goes here — double-click to edit.'; p.style.cssText = 'font-size:12px;color:#6b7280;margin:0 0 12px;line-height:1.5;';
        const btn = doc.createElement('a'); btn.textContent = 'Learn More'; btn.setAttribute('href', 'index.html');
        btn.style.cssText = 'display:inline-block;padding:8px 16px;background:#4A0713;color:#FBBF24;border-radius:10px;font-weight:800;font-size:11px;text-decoration:none;';
        body.appendChild(h); body.appendChild(p); body.appendChild(btn);
        card.appendChild(img); card.appendChild(body);
        return card;
      },
      ctaBanner: () => {
        const wrap = doc.createElement('div');
        wrap.style.cssText = 'background:linear-gradient(135deg,#4A0713,#E59819);border-radius:20px;padding:32px 24px;text-align:center;margin:16px 0;color:#fff;';
        const h = doc.createElement('h2'); h.textContent = 'Limited Time Offer'; h.style.cssText = 'font-weight:900;font-size:24px;margin:0 0 8px;color:#fff;';
        const p = doc.createElement('p'); p.textContent = 'Edit this banner text to promote your best deal.'; p.style.cssText = 'font-size:13px;margin:0 0 16px;opacity:.9;color:#fff;';
        const btn = doc.createElement('a'); btn.textContent = 'Shop Now'; btn.setAttribute('href', 'category.html');
        btn.style.cssText = 'display:inline-block;padding:10px 24px;background:#fff;color:#4A0713;border-radius:999px;font-weight:900;font-size:12px;text-decoration:none;';
        wrap.appendChild(h); wrap.appendChild(p); wrap.appendChild(btn);
        return wrap;
      },
      testimonialCard: () => {
        const wrap = doc.createElement('div');
        wrap.style.cssText = 'max-width:300px;background:#fff7ed;border:1px solid #fed7aa;border-radius:16px;padding:18px;margin:12px 0;';
        const stars = doc.createElement('div'); stars.textContent = '★★★★★'; stars.style.cssText = 'color:#E59819;font-size:14px;margin-bottom:8px;';
        const quote = doc.createElement('p'); quote.textContent = '"Double-click to edit this customer quote."'; quote.style.cssText = 'font-size:12px;color:#374151;font-style:italic;margin:0 0 10px;line-height:1.5;';
        const name = doc.createElement('p'); name.textContent = 'Customer Name'; name.style.cssText = 'font-size:11px;font-weight:900;color:#4A0713;margin:0;';
        wrap.appendChild(stars); wrap.appendChild(quote); wrap.appendChild(name);
        return wrap;
      },
      featureRow: () => {
        const wrap = doc.createElement('div');
        wrap.style.cssText = 'display:flex;align-items:center;gap:14px;padding:14px;background:#fff;border-radius:14px;border:1px solid #f3f4f6;margin:8px 0;';
        const icon = doc.createElement('span'); icon.innerHTML = '<i class="fas fa-check"></i>';
        icon.style.cssText = 'display:flex;align-items:center;justify-content:center;width:40px;height:40px;background:#4A0713;color:#FBBF24;border-radius:50%;font-size:16px;flex-shrink:0;';
        const text = doc.createElement('div');
        const h = doc.createElement('h4'); h.textContent = 'Feature Title'; h.style.cssText = 'font-weight:900;font-size:13px;color:#111827;margin:0 0 2px;';
        const p = doc.createElement('p'); p.textContent = 'Short feature description.'; p.style.cssText = 'font-size:11px;color:#6b7280;margin:0;';
        text.appendChild(h); text.appendChild(p);
        wrap.appendChild(icon); wrap.appendChild(text);
        return wrap;
      }
    };
  }

  function insertElement(type) {
    if (!state.doc || state.previewMode) return;
    const factory = ELEMENT_TEMPLATES(state.win)[type] || BLOCK_TEMPLATES(state.win)[type];
    if (!factory) return;
    pushUndo();
    const newEl = factory();
    const insertId = '__insert_' + Date.now().toString(36) + '_' + (insertCounter++);
    newEl.setAttribute('data-ed-id', insertId);

    let parent, refNode;
    if (state.selectedEl && !isLocked(state.selectedEl) && state.selectedEl !== state.doc.body) {
      parent = state.selectedEl.parentElement;
      refNode = state.selectedEl.nextSibling;
    } else {
      parent = state.doc.body;
      refNode = null;
    }
    parent.insertBefore(newEl, refNode);

    const patches = pagePatches();
    patches[insertId] = { parentPath: getPath(parent), html: newEl.outerHTML };
    savePatches();

    selectElement(newEl);
    renderLayers();
    flashToast('Element added — edit it in the panel on the right');
  }

  // ------------------------------------------------------------- layers tree
  function escapeAttr(str) {
    return String(str).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
  }

  const SKIP_LAYER_TAGS = new Set(['SCRIPT', 'STYLE', 'LINK', 'META', 'I', 'SVG', 'PATH', 'BR', 'NOSCRIPT']);
  let layerNodeCount = 0;

  function buildLayerTree(el, depth) {
    if (!el || el.nodeType !== 1 || SKIP_LAYER_TAGS.has(el.tagName)) return '';
    if (depth > 7 || layerNodeCount > 260) return '';
    layerNodeCount++;

    const locked = isLocked(el);
    const path = getPath(el);
    const isActive = !locked && state.selectedPath === path;
    let html = `<div class="ed-layer-item${locked ? ' locked' : ''}${isActive ? ' active' : ''}" style="padding-left:${depth * 11}px" data-path="${escapeAttr(path)}" title="${locked ? 'Data-driven — not editable here' : ''}">${locked ? '<i class="fas fa-lock" style="font-size:8px;margin-right:4px"></i>' : ''}${describeEl(el)}</div>`;

    if (!locked) {
      Array.from(el.children).forEach((child) => { html += buildLayerTree(child, depth + 1); });
    }
    return html;
  }

  function renderLayers() {
    const container = document.getElementById('ed-layers-tree');
    if (!container || !state.doc || !state.doc.body) return;
    layerNodeCount = 0;
    // Skip rendering a row for <body> itself (isLocked() always flags it, to
    // keep it un-selectable) — start the tree from its children instead.
    let html = '';
    Array.from(state.doc.body.children).forEach((child) => { html += buildLayerTree(child, 0); });
    container.innerHTML = html || '<p class="ed-empty-hint" style="padding:10px">No layers found.</p>';
    container.querySelectorAll('.ed-layer-item:not(.locked)').forEach((item) => {
      item.addEventListener('click', () => {
        const path = item.dataset.path;
        const el = state.doc.querySelector(path);
        if (el) {
          selectElement(el);
          try { el.scrollIntoView({ block: 'center', behavior: 'smooth' }); } catch (e) {}
        }
      });
    });
  }

  // ------------------------------------------------------------ properties panel
  function bindStyleInput(id, cssProp, unit, format) {
    const input = document.getElementById(id);
    if (!input || input.dataset.bound) return;
    input.dataset.bound = '1';
    let started = false;
    const apply = () => {
      if (!state.selectedEl) return;
      if (!started) { pushUndo(); started = true; }
      const val = format ? format(input.value) : (input.value + (unit || ''));
      state.selectedEl.style[cssProp] = val;
      renderOverlay();
      const valueLabel = document.getElementById(id.replace('-range', '-value'));
      if (valueLabel) valueLabel.textContent = val;
    };
    input.addEventListener('input', apply);
    input.addEventListener('change', () => {
      if (!state.selectedEl) return;
      apply();
      commitStyle(state.selectedEl, [cssProp]);
      started = false;
    });
  }

  function renderPropertiesPanel() {
    const empty = document.getElementById('ed-empty-hint');
    const props = document.getElementById('ed-props');
    if (!empty || !props) return;

    if (!state.selectedEl) {
      empty.style.display = 'block';
      props.style.display = 'none';
      return;
    }
    empty.style.display = 'none';
    props.style.display = 'block';

    const el = state.selectedEl;
    document.getElementById('ed-el-tag-label').textContent = describeEl(el);
    document.getElementById('ed-el-id-label').textContent = '#' + elementDisplayId(el);

    document.getElementById('ed-move-up-btn').disabled = !el.previousElementSibling;
    document.getElementById('ed-move-down-btn').disabled = !el.nextElementSibling;
    const inBlock = !!findInsertedRoot(el);
    const resetBtn = document.getElementById('ed-reset-element-btn');
    resetBtn.disabled = inBlock;
    resetBtn.title = inBlock ? "Newly added elements/blocks don't have a previous version — use Delete instead" : '';

    const cs = state.win.getComputedStyle(el);
    document.getElementById('ed-width-input').value = Math.round(el.getBoundingClientRect().width);
    document.getElementById('ed-height-input').value = Math.round(el.getBoundingClientRect().height);
    document.getElementById('ed-bg-color-input').value = rgbToHex(cs.backgroundColor) || '#ffffff';
    document.getElementById('ed-text-color-input').value = rgbToHex(cs.color) || '#000000';

    const bgImage = cs.backgroundImage || 'none';
    let bgType = 'solid';
    if (bgImage.includes('gradient')) bgType = 'gradient';
    else if (bgImage.includes('url(')) bgType = 'image';
    else if (rgbToHex(cs.backgroundColor) === null || cs.backgroundColor === 'rgba(0, 0, 0, 0)') bgType = 'none';
    document.getElementById('ed-bg-type').value = bgType;
    showBackgroundRows(bgType);

    const fs = parseInt(cs.fontSize) || 14;
    document.getElementById('ed-fontsize-range').value = fs;
    document.getElementById('ed-fontsize-value').textContent = fs + 'px';

    const pad = parseInt(cs.paddingTop) || 0;
    document.getElementById('ed-padding-range').value = pad;
    document.getElementById('ed-padding-value').textContent = pad + 'px';

    const radius = parseInt(cs.borderRadius) || 0;
    document.getElementById('ed-radius-range').value = radius;
    document.getElementById('ed-radius-value').textContent = radius + 'px';

    const mediaSection = document.getElementById('ed-media-section');
    mediaSection.style.display = ['IMG', 'VIDEO'].includes(el.tagName) ? 'block' : 'none';

    const linkSection = document.getElementById('ed-link-section');
    linkSection.style.display = el.tagName === 'A' ? 'block' : 'none';
    if (el.tagName === 'A') {
      const href = el.getAttribute('href') || '';
      const targetSelect = document.getElementById('ed-link-target');
      const known = Array.from(targetSelect.options).some((o) => o.value === href);
      targetSelect.value = known ? href : '__custom__';
      document.getElementById('ed-link-custom').value = href;
    }
  }

  // A stable, human-shareable ID for whatever is selected — the same
  // underlying element (existing HTML or something added via the palette)
  // always shows the same ID, so you can confirm "this is the button I set
  // the redirect on" before/after a reload.
  function elementDisplayId(el) {
    const ownId = el.getAttribute && el.getAttribute('data-ed-id');
    if (ownId && ownId.indexOf('__insert_') === 0) return ownId.replace('__insert_', 'new-');
    const path = getPath(el);
    let h = 0;
    for (let i = 0; i < path.length; i++) h = (h * 31 + path.charCodeAt(i)) | 0;
    return 'L-' + Math.abs(h).toString(36);
  }

  function rgbToHex(rgb) {
    const m = rgb && rgb.match(/\d+/g);
    if (!m || m.length < 3) return null;
    return '#' + m.slice(0, 3).map((n) => (+n).toString(16).padStart(2, '0')).join('');
  }

  function showBackgroundRows(type) {
    document.getElementById('ed-bg-solid-row').style.display = type === 'solid' ? 'block' : 'none';
    document.getElementById('ed-bg-gradient-row').style.display = type === 'gradient' ? 'block' : 'none';
    document.getElementById('ed-bg-image-row').style.display = type === 'image' ? 'block' : 'none';
  }

  function bindBackgroundControls() {
    document.getElementById('ed-bg-type').addEventListener('change', (e) => {
      const type = e.target.value;
      showBackgroundRows(type);
      if (!state.selectedEl) return;
      pushUndo();
      const el = state.selectedEl;
      if (type === 'none') {
        el.style.background = 'none';
        commitStyle(el, ['background']);
      } else if (type === 'solid') {
        el.style.backgroundImage = '';
        el.style.backgroundColor = document.getElementById('ed-bg-color-input').value;
        commitStyle(el, ['backgroundImage', 'backgroundColor']);
      } else if (type === 'gradient') {
        applyGradient(el);
      }
      // 'image' type waits for a file to be chosen below
    });

    function applyGradient(el) {
      const c1 = document.getElementById('ed-grad-color1').value;
      const c2 = document.getElementById('ed-grad-color2').value;
      const angle = document.getElementById('ed-grad-angle').value;
      el.style.backgroundImage = `linear-gradient(${angle}deg, ${c1}, ${c2})`;
      commitStyle(el, ['backgroundImage']);
    }
    ['ed-grad-color1', 'ed-grad-color2'].forEach((id) => {
      document.getElementById(id).addEventListener('change', () => {
        if (!state.selectedEl) return;
        pushUndo();
        applyGradient(state.selectedEl);
      });
    });
    const angleInput = document.getElementById('ed-grad-angle');
    let angleStarted = false;
    angleInput.addEventListener('input', () => {
      document.getElementById('ed-grad-angle-value').textContent = angleInput.value + 'deg';
      if (!state.selectedEl) return;
      if (!angleStarted) { pushUndo(); angleStarted = true; }
      applyGradient(state.selectedEl);
    });
    angleInput.addEventListener('change', () => { angleStarted = false; });

    document.getElementById('ed-bg-image-file').addEventListener('change', (e) => {
      const file = e.target.files[0];
      if (!file || !state.selectedEl) return;
      const reader = new FileReader();
      reader.onload = () => {
        pushUndo();
        const el = state.selectedEl;
        const size = document.getElementById('ed-bg-image-size').value;
        el.style.backgroundImage = `url("${reader.result}")`;
        el.style.backgroundSize = size;
        el.style.backgroundPosition = 'center';
        el.style.backgroundRepeat = 'no-repeat';
        commitStyle(el, ['backgroundImage', 'backgroundSize', 'backgroundPosition', 'backgroundRepeat']);
        flashToast('Background image set (saved locally)');
      };
      reader.readAsDataURL(file);
    });
    document.getElementById('ed-bg-image-size').addEventListener('change', (e) => {
      if (!state.selectedEl) return;
      pushUndo();
      state.selectedEl.style.backgroundSize = e.target.value;
      commitStyle(state.selectedEl, ['backgroundSize']);
    });
  }

  function bindWidthHeightInputs() {
    ['ed-width-input', 'ed-height-input'].forEach((id, idx) => {
      const input = document.getElementById(id);
      input.addEventListener('change', () => {
        if (!state.selectedEl) return;
        pushUndo();
        const prop = idx === 0 ? 'width' : 'height';
        state.selectedEl.style.boxSizing = 'border-box';
        state.selectedEl.style[prop] = input.value + 'px';
        commitStyle(state.selectedEl, ['boxSizing', prop]);
        renderOverlay();
      });
    });
  }

  function bindLinkInputs() {
    document.getElementById('ed-link-target').addEventListener('change', (e) => {
      if (!state.selectedEl || e.target.value === '__custom__') return;
      pushUndo();
      state.selectedEl.setAttribute('href', e.target.value);
      commitAttr(state.selectedEl, 'href', e.target.value);
      renderPropertiesPanel();
    });
    document.getElementById('ed-link-custom').addEventListener('change', (e) => {
      if (!state.selectedEl) return;
      pushUndo();
      state.selectedEl.setAttribute('href', e.target.value);
      commitAttr(state.selectedEl, 'href', e.target.value);
    });
  }

  function bindMediaInput() {
    document.getElementById('ed-media-file-input').addEventListener('change', (e) => {
      const file = e.target.files[0];
      if (!file || !state.selectedEl) return;
      const reader = new FileReader();
      reader.onload = () => {
        pushUndo();
        state.selectedEl.setAttribute('src', reader.result);
        commitAttr(state.selectedEl, 'src', reader.result);
        flashToast('Media replaced (saved locally in this browser)');
      };
      reader.readAsDataURL(file);
    });
  }

  function populateSwatches() {
    const box = document.getElementById('ed-swatches');
    if (!box) return;
    let swatches = ['#4A0713', '#E59819', '#FBBF24', '#32040C', '#FFF9ED', '#111827', '#ffffff'];
    try {
      if (state.win && state.win.THEME_PRESETS) {
        const fromPresets = state.win.THEME_PRESETS.flatMap((p) => p.swatches || []);
        if (fromPresets.length) swatches = [...new Set([...swatches, ...fromPresets])].slice(0, 24);
      }
    } catch (e) {}
    box.innerHTML = swatches.map((hex) => `<span class="ed-swatch" style="background:${hex}" data-hex="${hex}" title="${hex}"></span>`).join('');
    box.querySelectorAll('.ed-swatch').forEach((sw) => {
      sw.addEventListener('click', () => {
        if (!state.selectedEl) return;
        pushUndo();
        state.selectedEl.style.backgroundImage = '';
        state.selectedEl.style.backgroundColor = sw.dataset.hex;
        commitStyle(state.selectedEl, ['backgroundImage', 'backgroundColor']);
        renderPropertiesPanel();
      });
    });
  }

  // ------------------------------------------------------------- delete / reset
  function deleteSelected() {
    if (!state.selectedEl) return;
    if (!confirm('Remove this element from the page? (local only, undoable)')) return;
    pushUndo();
    const el = state.selectedEl;
    const patches = pagePatches();
    const insertedRoot = findInsertedRoot(el);
    if (insertedRoot === el) {
      // deleting the whole inserted element/block
      delete patches[el.getAttribute('data-ed-id')];
      el.remove();
    } else if (insertedRoot) {
      // deleting one piece INSIDE a block — remove it, then re-save the
      // block's root with that piece now missing from its markup
      el.remove();
      syncInsertedNode(insertedRoot);
    } else {
      const path = getPath(el);
      if (!patches[path]) patches[path] = {};
      patches[path].deleted = true;
      el.remove();
    }
    savePatches();
    state.selectedEl = null;
    state.selectedPath = null;
    renderPropertiesPanel();
    renderOverlay();
    renderLayers();
  }

  function resetSelected() {
    if (!state.selectedEl) return;
    // Anything added via Elements/Blocks has no separate "original" to fall
    // back to (its saved record IS its current state) — the panel disables
    // this button for that case, so this only ever runs on a pre-existing
    // page element.
    if (findInsertedRoot(state.selectedEl)) return;
    pushUndo();
    const path = getPath(state.selectedEl);
    delete pagePatches()[path];
    savePatches();
    reloadAndApply();
  }

  function resetPage() {
    if (!confirm('Discard ALL local design changes on this page? This cannot be undone once you leave this page.')) return;
    state.patches[state.pageKey] = {};
    savePatches();
    state.undoStack = [];
    state.redoStack = [];
    updateUndoRedoButtons();
    reloadAndApply();
  }

  // ------------------------------------------------------------------ misc UI
  function togglePreview() {
    state.previewMode = !state.previewMode;
    const btn = document.getElementById('ed-preview-btn');
    if (btn) btn.classList.toggle('ed-btn-primary', state.previewMode);
    if (state.previewMode) { state.hoveredEl = null; }
    renderOverlay();
    flashStatus(state.previewMode ? 'Preview mode — click interactions are disabled' : 'Edit mode');
  }

  function setDevice(mode) {
    const frame = document.getElementById('ed-canvas-frame');
    if (!frame) return;
    const widths = { desktop: '100%', tablet: '768px', mobile: '390px' };
    frame.style.width = widths[mode] || '100%';
    frame.style.margin = mode === 'desktop' ? '0' : '16px auto';
    setTimeout(renderOverlay, 260);
  }

  function setSnap(on) { state.snapEnabled = on; }
  function setGridSize(px) { state.gridSnap = Number(px); }

  function setLeftTab(tab) {
    document.querySelectorAll('.ed-tab-btn').forEach((btn) => btn.classList.toggle('active', btn.dataset.tab === tab));
    document.querySelectorAll('.ed-tab-panel').forEach((panel) => panel.classList.toggle('active', panel.id === 'ed-tab-' + tab));
  }

  const SHAPE_RADIUS = { square: '0px', rounded: '12px', pill: '999px', circle: '50%' };
  function setShape(shape) {
    if (!state.selectedEl) return;
    pushUndo();
    const el = state.selectedEl;
    el.style.borderRadius = SHAPE_RADIUS[shape] || '0px';
    if (shape === 'circle') {
      // a clean circle needs equal width/height — default to the larger side if it isn't already square
      const rect = el.getBoundingClientRect();
      const side = Math.max(rect.width, rect.height, 40) + 'px';
      el.style.boxSizing = 'border-box';
      el.style.width = side;
      el.style.height = side;
      commitStyle(el, ['borderRadius', 'boxSizing', 'width', 'height']);
    } else {
      commitStyle(el, ['borderRadius']);
    }
    renderOverlay();
    renderPropertiesPanel();
  }

  function bindKeyboardShortcuts(target) {
    target.addEventListener('keydown', (e) => {
      const tag = (e.target && e.target.tagName) || '';
      if (['INPUT', 'TEXTAREA', 'SELECT'].includes(tag) || (e.target && e.target.isContentEditable)) return;
      const mod = e.ctrlKey || e.metaKey;
      if (mod && e.key.toLowerCase() === 'z' && !e.shiftKey) { e.preventDefault(); undo(); }
      else if ((mod && e.key.toLowerCase() === 'y') || (mod && e.shiftKey && e.key.toLowerCase() === 'z')) { e.preventDefault(); redo(); }
      else if ((e.key === 'Delete' || e.key === 'Backspace') && state.selectedEl) { e.preventDefault(); deleteSelected(); }
    });
  }

  let toastTimer = null;
  function flashToast(msg) {
    const el = document.getElementById('ed-toast-mini');
    if (!el) return;
    el.textContent = msg;
    el.classList.add('show');
    clearTimeout(toastTimer);
    toastTimer = setTimeout(() => el.classList.remove('show'), 2400);
  }
  function flashStatus(msg) {
    const el = document.getElementById('ed-status-text');
    if (el) el.textContent = msg;
  }

  // -------------------------------------------------------------------- init
  async function guardAdminAccess() {
    try {
      if (window.MiraDB && typeof MiraDB.getAdminSession === 'function') {
        const session = await MiraDB.getAdminSession();
        if (!session) { window.location.href = 'admin.html'; return false; }
        state.adminUserId = session.user && session.user.id;
        state.currentAdmin = await MiraDB.getCurrentAdminProfile();
      }
    } catch (e) { /* offline local testing — allow through */ }
    return true;
  }

  async function publishToCloud() {
    if (!window.MiraDB || typeof MiraDB.dbUpsertPageDesignPatches !== 'function') {
      flashToast('Cloud publish is unavailable right now — Supabase did not load.');
      return;
    }
    const btn = document.getElementById('ed-publish-btn');
    const original = btn.innerHTML;
    btn.disabled = true;
    btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Publishing…';

    const ok = await MiraDB.dbUpsertPageDesignPatches(state.pageKey, pagePatches(), state.adminUserId, MiraDB.adminClient);

    btn.disabled = false;
    btn.innerHTML = original;

    if (!ok) {
      flashToast('Publish failed — the change did not reach the cloud. Please retry.');
      return;
    }
    if (state.currentAdmin && typeof MiraDB.logAdminActivity === 'function') {
      MiraDB.logAdminActivity(state.currentAdmin, 'design.publish', PAGES[state.pageKey].label);
    }
    flashToast('Published! Live for every visitor now.');
    flashStatus('Published live · ' + new Date().toLocaleTimeString('en-IN'));
  }

  async function init() {
    await guardAdminAccess();
    bindKeyboardShortcuts(document);
    initDragHandle();
    initResizeHandle();
    bindWidthHeightInputs();
    bindLinkInputs();
    bindMediaInput();
    bindStyleInput('ed-fontsize-range', 'fontSize', 'px');
    bindStyleInput('ed-padding-range', 'padding', 'px');
    bindStyleInput('ed-radius-range', 'borderRadius', 'px');
    bindBackgroundControls();
    document.getElementById('ed-bg-color-input').addEventListener('change', (e) => {
      if (!state.selectedEl) return;
      pushUndo();
      state.selectedEl.style.backgroundImage = '';
      state.selectedEl.style.backgroundColor = e.target.value;
      commitStyle(state.selectedEl, ['backgroundImage', 'backgroundColor']);
    });
    document.getElementById('ed-text-color-input').addEventListener('change', (e) => {
      if (!state.selectedEl) return;
      pushUndo();
      state.selectedEl.style.color = e.target.value;
      commitStyle(state.selectedEl, ['color']);
    });
    window.addEventListener('resize', renderOverlay);
    loadPage('home');
  }

  document.addEventListener('DOMContentLoaded', init);

  return {
    loadPage, undo, redo, resetPage, resetSelected, deleteSelected,
    moveSibling, resetPosition, togglePreview, setDevice, setSnap, setGridSize,
    bringToFront, sendToBack, insertElement, setLeftTab, setShape,
    publishToCloud
  };
})();
