#!/usr/bin/env node
/**
 * Reads SUPABASE_URL / SUPABASE_ANON_KEY from the environment (populated
 * from .env locally, or injected directly by Vercel's Environment Variables
 * in production) and writes js/env-config.js — the one file the browser
 * loads to learn its own Supabase connection details.
 *
 * This keeps real values out of source control while still working with
 * plain static HTML/JS (no bundler needed): Vercel runs this as the build
 * step, so the generated file only ever exists in the deployed output, not
 * in the repo.
 */
const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, '..');

// Minimal .env loader (no dependency). Only used for local dev — Vercel
// injects its own env vars directly into process.env, no .env file involved.
const envPath = path.join(rootDir, '.env');
if (fs.existsSync(envPath)) {
  for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
    const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*?)\s*$/);
    if (!match || line.trim().startsWith('#')) continue;
    const key = match[1];
    let value = match[2] || '';
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    if (!(key in process.env)) process.env[key] = value;
  }
}

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error('[generate-env] Missing SUPABASE_URL or SUPABASE_ANON_KEY.');
  console.error('[generate-env] Local dev: copy .env.example to .env and fill in real values.');
  console.error('[generate-env] Vercel: set them in Project Settings -> Environment Variables.');
  process.exit(1);
}

const output = `// AUTO-GENERATED by scripts/generate-env.js at build time — do not edit or commit this file.
window.__ENV__ = {
  SUPABASE_URL: ${JSON.stringify(SUPABASE_URL)},
  SUPABASE_ANON_KEY: ${JSON.stringify(SUPABASE_ANON_KEY)}
};
`;

fs.writeFileSync(path.join(rootDir, 'js', 'env-config.js'), output);
console.log('[generate-env] Wrote js/env-config.js for', SUPABASE_URL);
