#!/usr/bin/env node
/**
 * Reads SUPABASE_URL / SUPABASE_ANON_KEY from the environment (populated
 * from .env locally, or injected directly by Vercel's Environment Variables
 * in production) and writes public/js/env-config.js — the one file the
 * legacy admin.html / design-editor.html pages load to learn their own
 * Supabase connection details.
 *
 * UPDATED for the React rebuild: the site now builds via Vite into dist/,
 * so this writes into public/js/ (which Vite copies verbatim into dist/js/)
 * instead of the old js/ path at the repo root. The React app itself does
 * NOT use this file — it reads import.meta.env.VITE_SUPABASE_URL /
 * VITE_SUPABASE_ANON_KEY directly (see src/lib/supabase.js), which Vite
 * populates natively from .env or from Vercel's Environment Variables as
 * long as they're prefixed VITE_.
 *
 * Rewritten as an ES module (import/export) because package.json now has
 * "type": "module" for Vite — require()/module.exports are not available
 * in that mode.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

// Minimal .env loader (no dependency). Only used for local dev — Vercel
// injects its own env vars directly into process.env, no .env file involved.
const envPath = path.join(rootDir, '.env');
if (fs.existsSync(envPath)) {
  for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
    const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*?)\s*$/);
    if (!match || line.trim().startsWith('#')) continue;
    const key = match[1];
    let value = match[2] || '';
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    if (!(key in process.env)) process.env[key] = value;
  }
}

// Accept either the legacy names or the VITE_-prefixed ones, so one .env
// file (with both sets of lines) can serve the legacy pages and the React
// app at once.
const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error('[generate-env] Missing SUPABASE_URL/VITE_SUPABASE_URL or SUPABASE_ANON_KEY/VITE_SUPABASE_ANON_KEY.');
  console.error('[generate-env] Local dev: copy .env.example to .env and fill in real values.');
  console.error('[generate-env] Vercel: set them in Project Settings -> Environment Variables.');
  process.exit(1);
}

const output = `// AUTO-GENERATED by scripts/generate-env.js at build time — do not edit or commit this file.
window.__ENV__ = {
  SUPABASE_URL: ${JSON.stringify(SUPABASE_URL)},
  SUPABASE_ANON_KEY: ${JSON.stringify(SUPABASE_ANON_KEY)}
};
`;

fs.mkdirSync(path.join(rootDir, 'public', 'js'), { recursive: true });
fs.writeFileSync(path.join(rootDir, 'public', 'js', 'env-config.js'), output);
console.log('[generate-env] Wrote public/js/env-config.js for', SUPABASE_URL);
